# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dlieeOEyCdgGnavJpgrYK4H5DmxuN-D6
"""

def check_link_safety(url):
    suspicious_keywords = ['login', 'verify', 'update', 'secure', 'bank', 'free', 'prize']
    if not url:
        return {"verdict": "❌ Invalid", "reason": "No URL provided."}

    url_lower = url.lower()
    if any(word in url_lower for word in suspicious_keywords):
        return {"verdict": "⚠️ Suspicious", "reason": "Contains suspicious keywords often found in phishing links."}
    elif url_lower.startswith("https://"):
        return {"verdict": "✅ Safe", "reason": "Secure HTTPS link and no suspicious keywords found."}
    else:
        return {"verdict": "⚠️ Suspicious", "reason": "URL is not using HTTPS."}